#!/usr/bin/env bash
# Set up an enginx server
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
strr="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sed -i "s/server_name _;/$strr/" /etc/nginx/sites-enabled/default
service nginx start
