#!/usr/bin/env bash
# Set up an enginx server
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
comm="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$comm/" /etc/nginx/sites-enabled/default
service nginx start
