#!/usr/bin/env bash
# script to install haproxy
apt-get -y update
apt-get -y install haproxy
setup="\
frontend http_front
    bind *:80
    mode http
    default_backend http_back
backend http_back
    balance roundrobin
    server 1183-web-01 35.196.60.116:80 check
    server 1183-web-02 54.221.176.56:80 check"
echo "$setup" >> /etc/haproxy/haproxy.cfg
service haproxy start
