#!/usr/bin/env bash
# Script to print 10 times with an if condition
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
