#!/usr/bin/env bash
# Script to print numbers using a case conditional
i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((i++))
done
