#!/usr/bin/env bash
# script to check information about a file
fl="holbertonschool"
if [ -e "$fl" ]
then
    echo "$fl file exists"
    if [ -s $fl ]
    then
	    echo "$fl file is not empty"
    else
	    echo "$fl file is empty"
    fi

    if [ -f $fl ]
    then
	echo "$fl is a regular file"
    fi
else
    echo "$fl file does not exist"
fi
