#!/usr/bin/env bash
# changes to nginx user
chmod 777 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache2
sudo -u nginx service nginx restart